//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public string names { get; set; }
        public string surname { get; set; }
        public string company_name { get; set; }
        public string country { get; set; }
        public string adress { get; set; }
        public string city { get; set; }
        public string postcode { get; set; }
        public Nullable<int> phone { get; set; }
        public string email { get; set; }
        public string notes { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
