//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.Comments1 = new HashSet<Comment>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string photo { get; set; }
        public string blog1 { get; set; }
        public string info_title { get; set; }
        public string date { get; set; }
        public string user_type { get; set; }
        public string comments { get; set; }
        public string text { get; set; }
        public string clink { get; set; }
        public string ulink { get; set; }
        public string comlink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments1 { get; set; }
    }
}
