//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class information
    {
        public int id { get; set; }
        public Nullable<decimal> number { get; set; }
        public string photo { get; set; }
        public string infoTitle { get; set; }
        public string inText { get; set; }
        public string icon { get; set; }
    }
}
