//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_s
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<double> total { get; set; }
        public string actions { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual user user { get; set; }
    }
}
