//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Billings = new HashSet<Billing>();
            this.boxes = new HashSet<box>();
            this.Order_s = new HashSet<Order_s>();
            this.selects = new HashSet<select>();
        }
    
        public int product_id { get; set; }
        public string em_title { get; set; }
        public string em_photo { get; set; }
        public string title { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<bool> availability { get; set; }
        public Nullable<int> tag_id { get; set; }
        public Nullable<int> photo_id { get; set; }
        public Nullable<double> product_number { get; set; }
        public Nullable<int> weight { get; set; }
        public string dimensions { get; set; }
        public string description { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<int> box_id { get; set; }
        public Nullable<int> select_id { get; set; }
        public Nullable<int> select_clock_id { get; set; }
        public Nullable<int> selectTableware_id { get; set; }
        public Nullable<int> select_vase_id { get; set; }
        public Nullable<int> select_shop_id { get; set; }
        public Nullable<int> leftselectId { get; set; }
        public string product_type { get; set; }
        public string clas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<box> boxes { get; set; }
        public virtual box box { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_s> Order_s { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual Product_tags Product_tags { get; set; }
        public virtual Product Products1 { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual select select { get; set; }
        public virtual selectclock selectclock { get; set; }
        public virtual selectShop selectShop { get; set; }
        public virtual selectTableware selectTableware { get; set; }
        public virtual vaseselect vaseselect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<select> selects { get; set; }
    }
}
