//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Send_question
    {
        public int id { get; set; }
        public string question_title { get; set; }
        public string text { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string message_text { get; set; }
    }
}
