//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int id { get; set; }
        public string Logo { get; set; }
        public string h_menu_name { get; set; }
        public string sell_text { get; set; }
        public string em_title { get; set; }
        public string contactTypes { get; set; }
        public string contact_links { get; set; }
        public string location { get; set; }
        public string phone { get; set; }
        public string mail { get; set; }
        public string weblink { get; set; }
        public string gallery_col { get; set; }
        public string photo { get; set; }
        public string Links { get; set; }
    }
}
