//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueMall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int Id { get; set; }
        public string emtitle { get; set; }
        public string emphoto { get; set; }
        public string title { get; set; }
        public string photo { get; set; }
        public string name { get; set; }
        public string profession { get; set; }
        public string persinfo { get; set; }
        public string link { get; set; }
    }
}
